/**
 * Full basemap style: Protomaps vector tiles (france.pmtiles) with layers
 * generated by @protomaps/basemaps (French labels) and a CUSTOM « control
 * room » theme derived from the neutral design tokens.
 *
 * - land #0B0F15, water #05070A;
 * - country borders in border-strong, regional limits dashed and discreet;
 * - motorways and expressways highlighted as service axes (light grey-blue
 *   with a soft halo); other roads very discreet;
 * - city names in text-muted, only the main cities at low zooms;
 * - basemap buildings extruded discreetly from zoom 15 (surface-2/-3).
 *
 * NO status color and NO accent in the basemap: those are reserved for the
 * sites. Points of interest (colored icons) and one-way arrows are dropped.
 */
import { layers as protomapsLayers, type Flavor } from "@protomaps/basemaps";
import type { LayerSpecification, StyleSpecification } from "maplibre-gl";
import { MAP_NEUTRAL, NEUTRAL } from "./theme";
import { ORTHO_LAYER_SPEC, ORTHO_SOURCE, orthoSource } from "./ortho";
import { mapAssetUrls } from "./urls";

/** Id of the vector basemap source. */
export const BASEMAP_SOURCE = "france";

/** Protomaps layers removed from the theme (colored POIs, arrows). */
export const DROPPED_LAYERS: ReadonlySet<string> = new Set(["pois", "roads_oneway"]);

const n = NEUTRAL;
const m = MAP_NEUTRAL;

/** Theme passed to @protomaps/basemaps: every color is a neutral token. */
export const VIGIE_FLAVOR: Flavor = {
  background: m.water,
  earth: m.land,
  park_a: m.landcover, park_b: m.landcover, hospital: m.land, industrial: m.landcover, school: m.land,
  wood_a: m.landcover, wood_b: m.landcover, pedestrian: m.land, scrub_a: m.landcover, scrub_b: m.landcover,
  glacier: m.landcover, sand: m.landcover, beach: m.landcover, aerodrome: m.landcover, runway: n.surface2,
  water: m.water, zoo: m.landcover, military: m.landcover,
  tunnel_other_casing: m.land, tunnel_minor_casing: m.land, tunnel_link_casing: m.land, tunnel_major_casing: m.land, tunnel_highway_casing: m.land,
  tunnel_other: m.minorRoad, tunnel_minor: m.minorRoad, tunnel_link: m.minorRoad, tunnel_major: m.majorRoad, tunnel_highway: m.highwayHalo,
  pier: n.surface2, buildings: n.surface2,
  minor_service_casing: m.land, minor_casing: m.land, link_casing: m.land,
  major_casing_late: m.land, highway_casing_late: m.highwayHalo,
  other: m.minorRoad, minor_service: m.minorRoad, minor_a: m.minorRoad, minor_b: m.minorRoad, link: m.majorRoad,
  major_casing_early: m.land, major: m.majorRoad, highway_casing_early: m.highwayHalo, highway: m.highway,
  railway: m.rail, boundaries: n.borderStrong,
  bridges_other_casing: m.land, bridges_minor_casing: m.land, bridges_link_casing: m.land, bridges_major_casing: m.land, bridges_highway_casing: m.highwayHalo,
  bridges_other: m.minorRoad, bridges_minor: m.minorRoad, bridges_link: m.majorRoad, bridges_major: m.majorRoad, bridges_highway: m.highway,
  roads_label_minor: n.borderStrong, roads_label_minor_halo: m.land, roads_label_major: n.textMuted, roads_label_major_halo: m.land,
  ocean_label: n.borderStrong, subplace_label: n.borderStrong, subplace_label_halo: m.land,
  city_label: n.textMuted, city_label_halo: m.land, state_label: n.borderStrong, state_label_halo: m.land,
  country_label: n.textMuted, address_label: n.borderStrong, address_label_halo: m.land,
  landcover: { barren: m.landcover, farmland: m.landcover, forest: m.landcover, glacier: m.landcover, grassland: m.landcover, scrub: m.landcover, urban_area: m.landcover },
};

/** Adjusts the generated Protomaps layers to the Vigie theme. */
export function themeLayers(generated: readonly LayerSpecification[]): LayerSpecification[] {
  const out: LayerSpecification[] = [];
  for (const layer of generated) {
    if (DROPPED_LAYERS.has(layer.id)) continue;

    if (layer.id === "buildings") {
      // Discreet extrusion of the basemap buildings from zoom 15.
      out.push({
        id: "buildings",
        type: "fill-extrusion",
        source: BASEMAP_SOURCE,
        "source-layer": "buildings",
        minzoom: 15,
        filter: ["in", ["get", "kind"], ["literal", ["building", "building_part"]]],
        paint: {
          "fill-extrusion-color": ["interpolate", ["linear"], ["coalesce", ["get", "height"], 6], 0, n.surface2, 30, n.surface3],
          "fill-extrusion-height": ["coalesce", ["get", "height"], 6],
          "fill-extrusion-base": ["coalesce", ["get", "min_height"], 0],
          "fill-extrusion-opacity": ["interpolate", ["linear"], ["zoom"], 15, 0, 16, 0.55],
        },
      });
      continue;
    }

    if (layer.id === "boundaries" && layer.type === "line") {
      // Regional limits: dashed and discreet.
      out.push({ ...layer, paint: { ...layer.paint, "line-color": n.borderStrong, "line-opacity": 0.45, "line-width": 0.6, "line-dasharray": ["literal", [3, 3]] } });
      continue;
    }
    if (layer.id === "boundaries_country" && layer.type === "line") {
      out.push({ ...layer, paint: { ...layer.paint, "line-color": n.borderStrong, "line-width": ["interpolate", ["linear"], ["zoom"], 4, 0.8, 10, 1.6] } });
      continue;
    }

    if (layer.id === "roads_highway" && layer.type === "line") {
      // Soft halo below the motorway line: the service axes stand out.
      out.push({
        ...layer,
        id: "roads_highway_glow",
        paint: {
          "line-color": m.highway,
          "line-opacity": 0.28,
          "line-blur": 3,
          "line-width": ["interpolate", ["exponential", 1.6], ["zoom"], 4, 2, 8, 4, 12, 7, 16, 16],
        },
      });
      out.push({
        ...layer,
        paint: { ...layer.paint, "line-color": m.highway, "line-width": ["interpolate", ["exponential", 1.6], ["zoom"], 4, 0.6, 6, 1.2, 12, 2, 15, 5, 18, 14] },
      });
      continue;
    }

    if (layer.id === "places_locality" && layer.type === "symbol") {
      // Low zooms: only the main cities (Protomaps min_zoom ≤ 5).
      const mainCities: unknown = ["any", [">=", ["zoom"], 7], ["<=", ["coalesce", ["get", "min_zoom"], 99], 5]];
      out.push({ ...layer, filter: ["all", layer.filter ?? true, mainCities] as never });
      continue;
    }

    out.push(layer);
  }
  return out;
}

/** Options of {@link buildBasemapStyle}. */
export interface BasemapStyleOptions {
  /** window.location.origin (runtime); "" gives relative URLs (tests). */
  origin: string;
  /** Add the aerial imagery (only when the manifest lists ortho-sites.pmtiles). */
  ortho: boolean;
  /** Attributions, plain text (see attribution.ts). */
  attributions: readonly string[];
}

/**
 * Builds the full basemap style.
 * @returns A MapLibre style; the site layers are added on top by layers/sites.ts.
 */
export function buildBasemapStyle({ origin, ortho, attributions }: BasemapStyleOptions): StyleSpecification {
  const urls = mapAssetUrls(origin);
  const layers = themeLayers(protomapsLayers(BASEMAP_SOURCE, VIGIE_FLAVOR, { lang: "fr" }) as LayerSpecification[]);
  if (ortho) {
    // Below the labels, above the ground layers.
    const firstSymbol = layers.findIndex((l) => l.type === "symbol");
    layers.splice(firstSymbol < 0 ? layers.length : firstSymbol, 0, ORTHO_LAYER_SPEC);
  }
  return {
    version: 8,
    name: "Vigie — fond complet",
    glyphs: urls.glyphs,
    sprite: urls.sprite,
    sources: {
      [BASEMAP_SOURCE]: { type: "vector", url: urls.basemap, attribution: attributions.join(" · ") },
      ...(ortho ? { [ORTHO_SOURCE]: orthoSource(urls.ortho) } : {}),
    },
    layers,
  };
}
