/**
 * Generates src/domain/fields/column-lengths.ts from prisma/schema.prisma:
 * the maximum length of every `@db.NVarChar(n)` / `@db.Char(n)` column of the
 * registry models (`null` for NVarChar(Max)). The edit forms and the server
 * validation read their `maxLength` from it; a unit test checks it is in sync.
 *
 *   pnpm fields:lengths
 */
import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { columnLengths } from "../src/domain/fields/schema-lengths";

const root = join(import.meta.dirname, "..");
const lengths = columnLengths(readFileSync(join(root, "prisma/schema.prisma"), "utf8"));
const body = Object.entries(lengths)
  .map(([id, n]) => `  "${id}": ${n === null ? "null" : n},`)
  .join("\n");
writeFileSync(
  join(root, "src/domain/fields/column-lengths.ts"),
  `/**
 * GENERATED by \`pnpm fields:lengths\` from prisma/schema.prisma — do not edit.
 * Maximum length of the text columns of the registry models (null = MAX).
 */
export const COLUMN_LENGTHS: Readonly<Record<string, number | null>> = {
${body}
};
`,
);
console.log(`${Object.keys(lengths).length} colonnes texte écrites dans src/domain/fields/column-lengths.ts`);
